#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
# bspc config borderless_monocle true
# bspc config gapless_monocle true

bspc config focus_follows_pointer true

$HOME/.config/polybar/launch.sh

# 40 works well with polybar
# bspc config top_padding 40

picom --config ~/.config/picom.conf

# for ~/projects/run
bspc rule -a Electron state=floating

# Was sort of working with nouveau
picom -b --unredir-if-possible --backend xr_glx_hybrid --glx-swap-method --use-damage --glx-no-stencil

# Float mpv windows
bspc rule -a mpv state=floating
