xrandr --output DVI-I-1 --mode 1920x1080 --rate 144

xrdb -merge -I$HOME ~/.Xresources

# set key repeat delay and rate
xset r rate 200 50

# https://wiki.archlinux.org/index.php/Java#Non-reparenting_window_managers_.2F_Grey_window_.2F_Programs_not_drawing_properly
export _JAVA_AWT_WM_NONREPARENTING=1

feh --bg-scale ~/arch/DSCF3205.jpg &
  sxhkd &
  exec bspwm
